repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: ^\.github/
      - id: end-of-file-fixer
        exclude: ^\.github/
      - id: check-yaml
        args: [--unsafe]
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        types_or: [python, pyi]
        files: ^backend/
      - id: ruff-format
        types_or: [python, pyi]
        files: ^backend/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        additional_dependencies:
          - types-pyyaml>=6.0.12
          - pydantic[email]==2.11.9
          - pydantic-settings==2.11.0
          - fastapi>=0.111.0
          - click>=8.1.7
          - rich-click>=1.8.0
        args: [--strict, --ignore-missing-imports]
        files: ^backend/
        exclude: ^backend/(tests/|docs/)

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--strict]

  # Poetry check removed - using hatchling build backend instead

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.29.2
    hooks:
      - id: check-github-workflows
        args: [--verbose]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]
        exclude: ^(\.vscode/|\.github/dependabot\.yml)

  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c "cd backend && pytest"
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
        args: [--tb=short, -q]

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
